<a href="https://colab.research.google.com/github/mahajanashita/irisclassification/blob/main/yiris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv("/content/drive/My Drive/Iris.csv")

data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
import keras
from keras.layers import Dense
from keras.models import Sequential
import pydot
import graphviz
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
from IPython.display import SVG


In [ ]:
x=data.iloc[:,0:5].values
y=data.iloc[:,5].values
from sklearn.preprocessing import LabelEncoder
lbx_1=LabelEncoder()
y1=lbx_1.fit_transform(y)
# work on missing values
y=pd.get_dummies(y1).values 

In [ ]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
model=Sequential()

#first layer
model.add(Dense(5,input_shape=[10, 5],activation="relu"))
#second layer
model.add(Dense(3,activation="softmax"))


In [ ]:
model.compile(optimizer="Adam",loss="categorical_crossentropy",metrics=['accuracy'])

In [ ]:
model.fit(x_train ,y_train , batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 20.9158 - accuracy: 0.6500
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 19.9403 - accuracy: 0.6917
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 18.9150 - accuracy: 0.6917
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 17.9562 - accuracy: 0.6917
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 17.0168 - accuracy: 0.6917
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 16.0413 - accuracy: 0.6917
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 15.1539 - accuracy: 0.6917
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 14.3009 - accuracy: 0.6917
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 13.4197 - accuracy: 0.6917
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 12.6569 - accuracy: 0.6917

In [ ]:
y_pred=model.predict(x_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test_class,y_pred_class))
print(classification_report(y_test_class,y_pred_class))

[[11  0  0]
 [ 0 10  3]
 [ 0  2  4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.83      0.77      0.80        13
           2       0.57      0.67      0.62         6

    accuracy                           0.83        30
   macro avg       0.80      0.81      0.81        30
weighted avg       0.84      0.83      0.84        30



In [ ]:
26/30

0.8666666666666667

In [2]:
!git clone https://github.com/mahajanashita/irisclassification.git

fatal: destination path 'irisclassification' already exists and is not an empty directory.
